name: deploy # (0) GitHub Action에서 보여질 이름을 지정합니다. 

on:
  push:
    branches:
      - master


jobs:
  build: 
    runs-on: ubuntu-latest # (4) 해당 스크립트를 작동할 OS 입니다.
    permissions: 
      contents: read 
      packages: write

    steps:
    - name: Checkout 
      uses: actions/checkout@v3  # (5) 프로젝트 코드를 CheckOut합니다.    
      
    - name: Set up JDK 8 
      uses: actions/setup-java@v3 # (6) 
      with:
        java-version: '1.8'
        distribution: 'temurin' 
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew # (7)
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build -x test # (8)
      shell: bash
